apiVersion: v1
kind: Service
metadata:
  name: jsproject
spec:
  selector:
    app: jsproject
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsproject
  labels:
    app: jsproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jsproject
  template:
    metadata:
      labels:
        app: jsproject
    spec:
      containers:
        - name: jsproject
          image: mo2000hit/jsproject:1.0.0
          ports:
            - containerPort: 80
          imagePullPolicy: Always
